"""change

Revision ID: 125508b396e9
Revises: dc5f8713599d
Create Date: 2023-07-19 20:27:42.530985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125508b396e9'
down_revision = 'dc5f8713599d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
