"""remove password

Revision ID: a3ba5caa32c0
Revises: 125508b396e9
Create Date: 2023-07-19 20:31:44.729858

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a3ba5caa32c0"
down_revision = "125508b396e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
